// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
       case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows; 
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// For Firebase JS SDK v7.20.0 and later, measurementId is optional
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBW4EyMAoPmZww2zCcDaEpuk2cLG2IdQi8",
    authDomain: "rentmobile-c4616.firebaseapp.com",
    projectId: "rentmobile-c4616",
    storageBucket: "rentmobile-c4616.appspot.com",
    messagingSenderId: "900220872409",
    appId: "1:900220872409:web:049932229642827609c0c8",
    measurementId: "G-R02MV6BQ0T"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyQ3xVDtU7XaT06-tJIsO3vkVKZlEjnA',
    appId: '1:900220872409:android:1e13d7fc645a491c09c0c8',
    messagingSenderId: '89292047322',
    projectId: 'rentmobile-c4616',
    storageBucket: "rentmobile-c4616.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXsQzrge7GpY41FJeLzrF_NP9416RSd_Q',
    appId: '1:900220872409:ios:2ade94213bd92d8309c0c8',
    messagingSenderId: '900220872409',
    projectId: 'rentmobile-c4616',
    storageBucket: 'rentmobile-c4616.appspot.com',
    iosBundleId: 'com.example.rentMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXsQzrge7GpY41FJeLzrF_NP9416RSd_Q',
    appId: '1:900220872409:ios:2ade94213bd92d8309c0c8',
    messagingSenderId: '900220872409',
    projectId: 'rentmobile-c4616',
    storageBucket: 'rentmobile-c4616.appspot.com',
    iosBundleId: 'com.example.rentMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4EyMAoPmZww2zCcDaEpuk2cLG2IdQi8',
    appId: '1:900220872409:web:f740b6515e1bf33f09c0c8',
    messagingSenderId: '900220872409',
    projectId: 'rentmobile-c4616',
    authDomain: 'rentmobile-c4616.firebaseapp.com',
    storageBucket: 'rentmobile-c4616.appspot.com',
    measurementId: 'G-8RV9929GFF',
  ); 
}
